### ISSUE TITLE
Memory leak in python tf_service nodes

### ISSUE THREAD

**Issue by vinaykumarhegde** [magazino/tf_service#16]
Running a python tf_service module slowly leaks memory over time. Here's the example code I tested with:

```
import tf_service
import rospy

tf_buffer= None

def handle_pose(t):
    trans = tf_buffer.lookup_transform(
        'map', 'base_link', rospy.Time(), rospy.Duration(1.0))        
    #  some processing...



if __name__ == '__main__':
    rospy.init_node('test_node')
    tf_buffer = tf_service.BufferClient("/tf_service")
    tf_buffer.wait_for_server(timeout=rospy.Duration(2))
    rospy.Timer(rospy.Duration(0.02), handle_pose)
    rospy.spin()

```

And monitor it's memory:
```
watch ps -o pid,rss,args -p $(rosnode info /test_node  | grep Pid | cut -d ' ' -f2)
```

You could see the memory increase over time. From [Pybind11 return policy doc](https://pybind11.readthedocs.io/en/stable/advanced/functions.html?highlight=delete()#return-value-policies), I believe `return_value_policy::take_ownership` makes more sense for [L71](https://github.com/magazino/tf_service/blob/c9a21706638b757d90cc4bc38ad34b8e7e319b94/src/python_bindings/buffer_client_py.cc#L71) and [L81](https://github.com/magazino/tf_service/blob/c9a21706638b757d90cc4bc38ad34b8e7e319b94/src/python_bindings/buffer_client_py.cc#L81)? It seems to work on my testing.

**Comment by MichaelGrupp** [comment]
`take_ownership` does not help in my tests. I debugged and found that the timestamp of the returned `TransformStamped` is not properly garbage collected.

The [pympler](https://pympler.readthedocs.io/en/latest/) profiler (`apt install python3-pympler`) shows that a new instance of `rospy.rostime.Time` is added for every call to `lookup_transform`, while the object count should stay constant after initialization in this loop:
```
import rospy
import tf2_ros
from pympler.tracker import SummaryTracker

import tf_service

if __name__ == "__main__":
    tracker = SummaryTracker()

    rospy.init_node("client_test_py")

    buffer = tf_service.BufferClient("/tf_service")
    buffer.wait_for_server(rospy.Duration(10))

    rate = rospy.Rate(1)
    while not rospy.is_shutdown():
        buffer.lookup_transform("map", "base_link", rospy.Time(0),
                                rospy.Duration(1))
        tracker.print_diff()
        rate.sleep()
```

I prepared a fix in the linked PR. With this I see no additional objects and constant memory. Travis CI is currently broken, but if you want you can try the patch in the meantime, to confirm that it also works for you.
